# Generated by Django 3.1.4 on 2020-12-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20201226_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='seats',
        ),
        migrations.AddField(
            model_name='listing',
            name='body_type',
            field=models.CharField(choices=[('Compact', 'Compact'), ('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Van', 'Van'), ('PickUp', 'PickUp'), ('Sport', 'Sport')], default='Body Types (All)', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year',
            field=models.CharField(choices=[('1990', 'Older than 1990'), ('1991', 'After 1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020')], default='Year (All)', max_length=20),
        ),
    ]
