# Generated by Django 3.1.4 on 2021-01-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20210101_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Doors (All)', max_length=20),
        ),
    ]
