# Generated by Django 3.1.4 on 2021-01-01 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_doors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='doors',
        ),
    ]
