# Generated by Django 3.1.4 on 2021-01-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='available',
            field=models.CharField(choices=[('False', 'No'), ('True', 'Yes')], default='No', max_length=50),
        ),
    ]
