# Generated by Django 3.1.4 on 2021-01-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20210101_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default='Transmission (All)', max_length=20),
        ),
    ]
