# Generated by Django 3.1.4 on 2021-01-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20210103_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contact_number',
            field=models.CharField(default='75 436 608', max_length=2002),
        ),
    ]
