# Generated by Django 3.1.4 on 2021-01-06 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_listing_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='engine',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
