# Generated by Django 3.1.4 on 2021-01-07 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_auto_20210107_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo_7',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_8',
        ),
    ]
