# Generated by Django 3.1.4 on 2021-01-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_auto_20210107_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo_7',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_8',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
