# Generated by Django 3.0.5 on 2021-01-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_auto_20210107_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
