# Generated by Django 3.0.5 on 2021-02-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_auto_20210216_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo_7',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_8',
        ),
    ]
