# Generated by Django 3.0.5 on 2021-02-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_auto_20210116_1925'),
        ('listings', '0021_auto_20210216_1155'),
    ]

    operations = [
    ]
