# Generated by Django 3.0.5 on 2021-03-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_merge_20210301_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='dealership',
            field=models.CharField(choices=[('Gaborone', 'Gaborone'), ('Francistown', 'Francistown')], default='Dealership (All)', max_length=20),
        ),
    ]
