# Generated by Django 3.0.5 on 2021-02-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_auto_20210223_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='dealership',
            field=models.CharField(choices=[('Gaborone', 'Gaborone')], default='Dealership (All)', max_length=20),
        ),
    ]
