# Generated by Django 3.0.5 on 2021-03-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_auto_20210223_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='contact_number',
            field=models.CharField(default='72 621 902', max_length=2002),
        ),
        migrations.AlterField(
            model_name='listing',
            name='dealership',
            field=models.CharField(choices=[('Palapye', 'Palapye')], default='Dealership (All)', max_length=20),
        ),
    ]
