# Generated by Django 3.0.5 on 2021-04-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_auto_20210303_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='dealership',
            field=models.CharField(choices=[('Windhoek', 'Windhoek'), ('Keetmanshoop', 'Keetmanshoop'), ('Francistown', 'Francistown')], default='Dealership (All)', max_length=20),
        ),
    ]
