# Generated by Django 3.0.5 on 2021-04-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_auto_20210424_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='extra_details',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_number',
            field=models.CharField(default='+264 81 350 6809', max_length=2002),
        ),
    ]
