# Generated by Django 3.0.5 on 2021-04-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_auto_20210424_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='contact_number',
            field=models.CharField(default='81 350 6809', max_length=2002),
        ),
        migrations.AlterField(
            model_name='listing',
            name='dealership',
            field=models.CharField(choices=[('Windhoek', 'Windhoek'), ('Keetmanshoop', 'Keetmanshoop')], default='Dealership (All)', max_length=20),
        ),
    ]
